### ISSUE TITLE
Requirements.txt and installation instruction needs update

### ISSUE THREAD

**Issue by mkcoldwolf** [tlaundal/dmcb#2]
Sorry im still a newbie on python and trying to install such amazing banner maker myself as http://status.mclive.eu/ dont support https :( 

and then i started to host this program myself and problems comes up
first, instruction is very unclear, there is two point need to be changed
- should state that it require python3, not 2
- the py file for testing up the program is `start.py` not `dmcb.py`

there is even more worse case, flask framework and Werkzeug this repo used is very old
in requirements.txt they only marked the min version
and the latest version of them does not work with the current code
this is what i changed to make it work:
```
Flask==0.10.1
Werkzeug==0.9.4
```
dont know which version is the latest compatible one as im not familiar with python :P

**Comment by tlaundal** [comment]
Hi, thanks for bringing up these issues. As you probably have figured out, I haven't actually run this in a while.
I'll make the necessary adjustments to `requirements.py` and the README.
